### PR TITLE
Implement compare_view

### PR DESCRIPTION
**Pull request by christopher-besch**

### CODE REVIEW

**Comment by kolibril13** [comment]
Thank you so much for the implementation, I really like it!
Some thoughts:
I am planning to make an applet out of this where the focus will be on explaining the image filters and how they are normally applied. 
While the current implementation looks really nice in the current context, as soon as the application will get more fleshed-out, I have the feeling that the compare_view has currently requires a bit too much user attention, I think minimalism is here the way to go. Therefore, my suggestion: We only keep the Horizontal mode, and drop the circle and drop the vertical mode. Then, It's also enough to have 2 images at a time, and we don't need the extra two canvas.
Also, can the drag and drop area be two small arrows, maybe something like this?
When there is only the horizontal slider, I think the image preview is also not required.
image

**Comment by kolibril13** [comment]
And another thing: Can the cats be replaced with an empty image for the default?
Maybe this might help there: https://stackoverflow.com/questions/9126105/blank-image-encoded-as-data-uri

**Comment by christopher-besch** [comment]
Those are all pretty easy things, I'll do them in the course of this week.

**Comment by christopher-besch** [comment]
@kolibril13, I've changed a few things. Using arrows instead of squares would be more difficult so I'd like to hear your feedback first. I tried to make it as minimal as possible so I hope this better suits your taste.
I think you should play around with the CSS-layouting a little; maybe having the canvas to the right of the drag target makes more sense. The size of the drag targets and canvas is also just a guess at the moment.

BTW: You can add as many `<div class="drag_target">` as you like here: https://github.com/kolibril13/pyscript-emoji-skimage/blob/6762b5a79932e0a9e5209e7e44369e9f52a00eea/index.html#L67-L74
Two are just the minimum.

**Comment by christopher-besch** [comment]
Fun Fact: Dynamically changing the images is something Juxtapose.js can't do, that's exactly the kind of thing compare_view is perfect for.

**Comment by kolibril13** [comment]
>  Fun Fact: Dynamically changing the images is something Juxtapose.js can't do, that's exactly the kind of thing compare_view is perfect for.

That is really great to hear! compare_view is indeed really neat and versatile, thank you so much for putting effort into it!

And yes, the compare applet looks now very nice and simple. And it does what it should do, thanks for implementing this!
I will play a bit with the CSS and let you know. 

Regarding the arrow: I've just designed this one in Affinity designer, maybe the SVG string can be included into the HTML?
```
<img width="561" alt="image" src="https://user-images.githubusercontent.com/44469195/182697708-dce62446-dfec-4298-9409-cc03a8e62499.png">

<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg width="100%" height="100%" viewBox="0 0 209 139" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"><path d="M67.91,0l73.135,0l-0,33.576l67.91,0l-104.478,104.478l-104.477,-104.478l67.91,0l0,-33.576Z" style="fill:#f00;"/></svg>
```

**Comment by kolibril13** [comment]
After some tinkering, I think I found a nice layout:
image
And this could be the same with the compare arrows:
image

**Pull request merged**
